### ISSUE TITLE
更新后京东无法打开

### ISSUE THREAD

**Issue by jackynx** [xcehnz/HistoryPrice#1]
原版0.16版正常使用，更新最新版0.17后打开卡在京东启动页

**Comment by xcehnz** [comment]
> 原版0.16版正常使用，更新最新版0.17后打开卡在京东启动页

更新京东到最新版试一下

**Comment by Suricher** [comment]
最新版0.17+最新版京东，jd偶尔会出现无响应的情况，有点频繁，手机魅族16。

**Comment by xcehnz** [comment]
> 最新版0.17+最新版京东，jd偶尔会出现无响应的情况，有点频繁，手机魅族16。

试一下0.18，我都没问题

**Comment by Suricher** [comment]
0.180版本好用，测试一下今天都没有无响应的情况了。


 
---原始邮件---
发件人: "kagura"<notifications@github.com&gt;
发送时间: 2019年10月31日 22:45:05
收件人: "xcehnz/HistoryPrice"<HistoryPrice@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Suricher"<1002075343@qq.com&gt;;
主题: Re: [xcehnz/HistoryPrice] 更新后京东无法打开 (#1)


 
最新版0.17+最新版京东，jd偶尔会出现无响应的情况，有点频繁，手机魅族16。
  
试一下0.18，我都没问题

**Comment by jackynx** [comment]
> > 最新版0.17+最新版京东，jd偶尔会出现无响应的情况，有点频繁，手机魅族16。
> 
> 试一下0.18，我都没问题

0.18京东正常了

**Comment by jackynx** [comment]
> > 最新版0.17+最新版京东，jd偶尔会出现无响应的情况，有点频繁，手机魅族16。
> 
> 试一下0.18，我都没问题

0.18还是会出现这种情况
